/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author batis
 */
public class venta extends javax.swing.JFrame {
       private static Connection conn;
         public static final String DRIVER="com.mysql.jdbc.Driver";
       
          public static final String USUARIO="root";
         public static final String PASSWORD="xboxONE.5";
         public static final String URL="jdbc:mysql://localhost:3306/basetienda";
         PreparedStatement ps;
         ResultSet rs;
         
       public static Connection getConnection(){
             conn=null;
             try {
                 Class.forName(DRIVER);
                 conn=(Connection) DriverManager.getConnection(URL, USUARIO, PASSWORD);
                 if(conn !=null){
                     System.out.print("conexcion establecida");
                 }
                 
                 
             }catch(ClassNotFoundException | SQLException e){
                 System.out.print("conexcion no establecida"+e);
                 
             }
    

    
    return conn;
       }

       

    /**
     * Creates new form venta
     */
    public venta() {
        initComponents();
    
          
        this.Tabv.setModel(venta);
         this.venta.addColumn("Codigo de producto");
        this.venta.addColumn("Marca de Producto");
        this.venta.addColumn("Nombre de producto");
        this.venta.addColumn("Descripcion de producto");
              this.venta.addColumn("Precio de producto");
     
       
            this.venta.addColumn("Cantidad de productos");
           this.venta.addColumn("Total de productos");
     
        
    }
    
    private void Limpiar(){
    
        this.cop.setText("");
        this.mp.setText("");
        this.np.setText("");
        this.dp.setText("");
        this.pp.setText("");
        this.cap.setText("");
      
        this.tp.setText("");
        this.ttp.setText("");
        this.cp.setText("");
        this.gp.setText("");
 
         this.camp.setText("");
         this.cn.setText("");
         this.ne.setText("");
    
    
}
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   DefaultTableModel venta=new DefaultTableModel();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabv = new javax.swing.JTable();
        cop = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cap = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pp = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        tp = new javax.swing.JTextField();
        cp = new javax.swing.JTextField();
        camp = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        dp = new javax.swing.JTextField();
        Validar = new javax.swing.JButton();
        np = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        ingresar = new javax.swing.JButton();
        gp = new javax.swing.JTextField();
        neto = new javax.swing.JButton();
        ne = new javax.swing.JTextField();
        s = new javax.swing.JButton();
        ttp = new javax.swing.JTextField();
        cn = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IrProducto = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        IrCita = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        IrCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        IrProveedor = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        IrCierre = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Co1 = new javax.swing.JButton();
        nn = new javax.swing.JButton();
        idc = new javax.swing.JTextField();
        idv = new javax.swing.JTextField();
        idp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(29, 58, 142));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CODIGO DE PRODUCTO");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        Tabv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabv);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 858, 312));
        jPanel1.add(cop, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 111, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("MARCA DEL PRODUCTO");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));
        jPanel1.add(mp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 111, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PRECIO DEL PRODUCTO");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));
        jPanel1.add(cap, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 133, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CANTIDAD DE PRODUCTO");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));
        jPanel1.add(pp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 111, -1));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jButton6.setText("GUARDAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 540, 140, -1));
        jPanel1.add(tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 0, -1));
        jPanel1.add(cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(859, 504, 111, -1));
        jPanel1.add(camp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1005, 504, 111, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("DESCPCION DE PRODUCTO");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));
        jPanel1.add(dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 111, -1));

        Validar.setBackground(new java.awt.Color(255, 255, 255));
        Validar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Validar.setText("VALIDAR");
        Validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidarActionPerformed(evt);
            }
        });
        jPanel1.add(Validar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, -1, -1));
        jPanel1.add(np, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 111, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("NOMBRE DE PRODUCTO");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        ingresar.setBackground(new java.awt.Color(255, 255, 255));
        ingresar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        ingresar.setText("INGRESAR");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        jPanel1.add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, -1, -1));
        jPanel1.add(gp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1152, 504, 111, -1));

        neto.setBackground(new java.awt.Color(255, 255, 255));
        neto.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        neto.setText("NETO");
        neto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netoActionPerformed(evt);
            }
        });
        jPanel1.add(neto, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, 111, -1));

        ne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neActionPerformed(evt);
            }
        });
        jPanel1.add(ne, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 504, 111, -1));

        s.setBackground(new java.awt.Color(255, 255, 255));
        s.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        s.setText("SALIR");
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });
        jPanel1.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 540, 112, -1));
        jPanel1.add(ttp, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 504, 111, -1));
        jPanel1.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 504, 111, -1));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("CANTIDAD NETO");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 474, -1, -1));

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("PRECIO NETO");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 474, -1, -1));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("TOTAL");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 474, -1, -1));

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("COBRO");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(889, 474, -1, -1));

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("CAMBIO");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1035, 474, -1, -1));

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("GANANCIA");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1169, 474, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(29, 58, 142));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PROVEEDOR.jpg"))); // NOI18N

        IrProducto.setBackground(new java.awt.Color(29, 58, 142));
        IrProducto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        IrProducto.setForeground(new java.awt.Color(255, 255, 255));
        IrProducto.setText("PRODUCTO");
        IrProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IrProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IrProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 110, 110));

        jPanel4.setBackground(new java.awt.Color(29, 58, 142));

        IrCita.setBackground(new java.awt.Color(29, 58, 142));
        IrCita.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        IrCita.setForeground(new java.awt.Color(255, 255, 255));
        IrCita.setText("CITA");
        IrCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrCitaActionPerformed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CITA_1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(IrCita))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IrCita, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, 110));

        jPanel5.setBackground(new java.awt.Color(29, 58, 142));

        IrCliente.setBackground(new java.awt.Color(29, 58, 142));
        IrCliente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        IrCliente.setForeground(new java.awt.Color(255, 255, 255));
        IrCliente.setText("CLIENTE");
        IrCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrClienteActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CLIENTE.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IrCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IrCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 80, 110));

        jPanel6.setBackground(new java.awt.Color(29, 58, 142));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PRODUCTO.jpg"))); // NOI18N

        IrProveedor.setBackground(new java.awt.Color(29, 58, 142));
        IrProveedor.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        IrProveedor.setForeground(new java.awt.Color(255, 255, 255));
        IrProveedor.setText("PROVEEDOR");
        IrProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IrProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(26, 26, 26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IrProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 120, 110));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logogrande.jpg"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 710, 80));

        jPanel8.setBackground(new java.awt.Color(29, 58, 142));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/CIERRE.jpg"))); // NOI18N

        IrCierre.setBackground(new java.awt.Color(29, 58, 142));
        IrCierre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        IrCierre.setForeground(new java.awt.Color(255, 255, 255));
        IrCierre.setText("CIERRE");
        IrCierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrCierreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(IrCierre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IrCierre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, 110));

        jButton7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/INFO.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 40));

        jButton1.setText("?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1490, 150));

        Co1.setBackground(new java.awt.Color(255, 255, 255));
        Co1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Co1.setText("COBRAR");
        Co1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Co1ActionPerformed(evt);
            }
        });
        jPanel1.add(Co1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, 112, -1));

        nn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        nn.setText("QUITAR");
        nn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nnActionPerformed(evt);
            }
        });
        jPanel1.add(nn, new org.netbeans.lib.awtextra.AbsoluteConstraints(903, 540, 120, 30));

        idc.setText("              1");
        idc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcActionPerformed(evt);
            }
        });

        idv.setText("2");
        idv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idvActionPerformed(evt);
            }
        });

        idp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(idp)
                    .addComponent(idv, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(idp, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(idv, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        Connection conn=null;
        try {
            conn= getConnection();
            ps=conn.prepareStatement("INSERT INTO ventas(id_Clientes,id_Productos,total_ventas,cobro_Ventas,cambio_ventas,ganancia_Ventas) VALUES(?,?,?,?,?,?)");
            ps.setString(1,idc.getText());
            ps.setString(2,idp.getText());
            ps.setString(3,ttp.getText());
            ps.setString(4,cp.getText());
            ps.setString(5,camp.getText());
            ps.setString(6,gp.getText());
            int res=ps.executeUpdate();
            if(res>0){
                     JOptionPane.showMessageDialog(null,"producto guardado");
                     Limpiar();
                    
                 }  else{
                      JOptionPane.showMessageDialog(null," Error al guardar producto");
                 }  
                 conn.close();
             }catch(Exception e){
                     System.err.println(e);
                     }
        
                         
      
    }//GEN-LAST:event_jButton6ActionPerformed

    
    
    private void ValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidarActionPerformed
        // TODO add your handling code here:
               Connection conn=null;
       
        try{
            conn= getConnection();
            ps=conn.prepareStatement("SELECT * FROM productos WHERE codigo_Producto=?");
             ps.setString(1,cop.getText());
            ResultSet rs=ps.executeQuery();
            if(rs.next()){
            idp.setText(rs.getString("id_Productos"));
              mp.setText(rs.getString("marca_producto"));
               np.setText(rs.getString("nombre_Productos"));
                dp.setText(rs.getString("descripcion_producto"));
                 pp.setText(rs.getString("PrecioF_Productos"));
              ;
                
          JOptionPane.showMessageDialog(null,"Producto Encontrado");
                     
                 }  else{
                      JOptionPane.showMessageDialog(null," Error al guardar produto");
                 }  
                 conn.close();
            
            
      
        }catch(SQLException ex){
            Logger.getLogger(venta.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_ValidarActionPerformed

      private void guardarde(){
            Connection conn=null;
        try {
            conn= getConnection();
            ps=conn.prepareStatement("INSERT INTO detalle_ventas(productos_id_Productos,ventas_id_Ventas,cod_pro,cant_venta) VALUES(?,?,?,?)");
            ps.setString(1,idp.getText());
            ps.setString(2,idv.getText());
            ps.setString(3,cop.getText());
            ps.setString(4,cap.getText());
            int res=ps.executeUpdate();
            if(res>0){
                      JOptionPane.showMessageDialog(null," Producto Ingresado");
                    
                 }  else{
                      JOptionPane.showMessageDialog(null," Error al guardar producto");
                 }  
                 conn.close();
             }catch(Exception e){
                     System.err.println(e);
                     }
        
                         
      
            
      
      }
      
     
    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
        // TODO add your handling code here:
         inv_final();
         guardarde();

        
         this.venta.addRow(new Object[]{
        this.cop.getText(),this.mp.getText(), this.np.getText(),
        this.dp.getText(),this.pp.getText(),this.cap.getText(),this.tp.getText()
        });
       Limpiar();
    }//GEN-LAST:event_ingresarActionPerformed

    private void netoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netoActionPerformed
        // TODO add your handling code here:
        double sumatoria;
        double sumatoriai=0;
        double sum;
        double su=0;
        int totalrow=Tabv.getRowCount();
        totalrow-=1;
        for (int i = 0; i <= (totalrow); i++) {
            sumatoria=Double.parseDouble(String.valueOf(Tabv.getValueAt(i, 6)));
            sumatoriai+=sumatoria;
            sum=Double.parseDouble(String.valueOf(Tabv.getValueAt(i, 5)));
            su+=sum;
          
   
            
        }
        ne.setText("S.    "+String.valueOf(sumatoriai));
          cn.setText("C.    "+String.valueOf(su));
    }//GEN-LAST:event_netoActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_sActionPerformed

    private void idpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpActionPerformed

    private void idcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idcActionPerformed

    private void neActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_neActionPerformed

    private void IrProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrProductoActionPerformed
        // TODO add your handling code here:
        Productos Productos= new Productos();
        Productos.setVisible(true);
       
    }//GEN-LAST:event_IrProductoActionPerformed

    private void IrCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrCitaActionPerformed
        // TODO add your handling code here:
        cita cita= new cita();
        cita.setVisible(true);
 
    }//GEN-LAST:event_IrCitaActionPerformed

    private void IrClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrClienteActionPerformed
        // TODO add your handling code here:
        cliente cliente= new cliente();
        cliente.setVisible(true);
    
    

    }//GEN-LAST:event_IrClienteActionPerformed

    private void IrProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrProveedorActionPerformed
        // TODO add your handling code here:
       Proveedores Provedores = new Proveedores();
        Provedores.setVisible(true);
           this.dispose();
        
       
    }//GEN-LAST:event_IrProveedorActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void IrCierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrCierreActionPerformed
        // TODO add your handling code here:
        cierres cierres= new cierres();
        cierres.setVisible(true);
    }//GEN-LAST:event_IrCierreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   vendedor vendedor= new vendedor();
        vendedor.setVisible(true);
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idvActionPerformed

    private void nnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nnActionPerformed
        // TODO add your handling code here:
       venta.removeRow(this.Tabv.getSelectedRow());
        
    }//GEN-LAST:event_nnActionPerformed

    private void Co1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Co1ActionPerformed
        // TODO add your handling code here:
        inv_final2();
    }//GEN-LAST:event_Co1ActionPerformed
public void inv_final(){
    double precio,cant,total,iva,preciof;
   
    precio=Double.parseDouble(this.pp.getText());
    
    cant=Double.parseDouble(this.cap.getText());

   
    iva=((precio)*(0.21));
    preciof=((precio)+(iva));
    total=((preciof)*(cant));
    this.tp.setText(String.valueOf(total));
 
   
}
public void inv_final2(){
    double  sumatoriai,cobro,cambio,ganancia;
   
     sumatoriai=Double.parseDouble(this.ttp.getText());
    
    cobro=Double.parseDouble(this.cp.getText());
    cambio=((cobro)-(sumatoriai));
    this.camp.setText(String.valueOf(cambio));  
 
     ganancia=((sumatoriai)-(cambio));
      this.gp.setText(String.valueOf(ganancia));  
   
}


    
    
    



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Co1;
    private javax.swing.JButton IrCierre;
    private javax.swing.JButton IrCita;
    private javax.swing.JButton IrCliente;
    private javax.swing.JButton IrProducto;
    private javax.swing.JButton IrProveedor;
    private javax.swing.JTable Tabv;
    private javax.swing.JButton Validar;
    private javax.swing.JTextField camp;
    private javax.swing.JTextField cap;
    private javax.swing.JTextField cn;
    private javax.swing.JTextField cop;
    private javax.swing.JTextField cp;
    private javax.swing.JTextField dp;
    private javax.swing.JTextField gp;
    private javax.swing.JTextField idc;
    private javax.swing.JTextField idp;
    private javax.swing.JTextField idv;
    private javax.swing.JButton ingresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mp;
    private javax.swing.JTextField ne;
    private javax.swing.JButton neto;
    private javax.swing.JButton nn;
    private javax.swing.JTextField np;
    private javax.swing.JTextField pp;
    private javax.swing.JButton s;
    private javax.swing.JTextField tp;
    private javax.swing.JTextField ttp;
    // End of variables declaration//GEN-END:variables
}
